apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "stickerbomb.fullname" . }}
  labels:
    {{- include "stickerbomb.labels" . | nindent 4 }}
rules:
  - apiGroups: ["stickerbomb.dev"]
    resources: ["labelers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["stickerbomb.dev"]
    resources: ["labelers/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
  {{- if .Values.clusterRules.strict }}
  {{- range .Values.clusterRules.rules }}
  - apiGroups: {{ .apiGroups }}
    resources: {{ .resources }}
    verbs: ["get", "list", "watch", "patch"]
  {{- end }}
  {{- else }}
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "patch"]
  {{- end }}
