apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "stickerbomb.fullname" . }}
  labels:
    {{- include "stickerbomb.labels" . | nindent 4 }}
rules:
  - apiGroups: ["stickerbomb.dev"]
    resources: ["labelers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["stickerbomb.dev"]
    resources: ["labelers/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
  {{- range .Values.clusterRoles.rules }}
  - apiGroups: {{- .apiGroups | toYaml | nindent 6 }}
    resources: {{- .resources | toYaml | nindent 6 }}
    verbs: ["get", "list", "watch", "patch"]
  {{- end }}
