apiVersion: v2
name: stickerbomb
description: Stickerbomb is a minimal label automation operator.
type: application
version: 0.1.0
appVersion: "0.1.0"

home: https://github.com/Shikachuu/stickerbomb
sources:
  - https://github.com/Shikachuu/stickerbomb
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/category: integration-delivery
