# yaml-language-server: $schema=values.schema.json
serviceAccount:
  create: true
  automount: true
  name: "stickerbomb"

clusterRules:
  strict: false

image:
  repository: stickerbomb
  pullPolicy: Always
  tag: ""

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

operator:
  logLevel: debug
  logFormat: text
