name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  formalities:
    name: Validate PR formalities
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          ignoreLabels: |
            dependabot

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          shared-key: "pr-${{github.event.pull_request.number}}"
          cache-all-crates: "true"

        # https://github.com/jdx/mise-action/issues/215
      - name: Make sure clippy and rustfmt are installed
        run: |
          export active_rust_toolchain=$(rustup show active-toolchain | cut -d' ' -f1)
          rustup component add --toolchain ${active_rust_toolchain} rustfmt clippy

      - name: Lint
        run: mise lint

      - name: Run CRD generate
        run: mise generate-crds

      - name: Check for changes
        run: |
          if ! git diff --exit-code; then
            echo "::error::Files are not up to date. Please run mise update-helm' and commit the changes."
            exit 1
          fi

      - name: Grype security check
        id: grype
        run: grype . -f medium --file grype.sarif
        continue-on-error: true

      - name: upload Grype scan SARIF report
        if: steps.grype.outcome == 'failure'
        uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
        with:
          sarif_file: grype.sarif

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          shared-key: "pr-${{github.event.pull_request.number}}"
          cache-all-crates: "true"

      - name: Install LCOV
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Run tests
        run: mise test

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@c18f1c00419937aa086a9a29d82a03912d160f4d # v6.0.0
        with:
          coverage-files: lcov.info
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
